resolver: lts-14.27

ghc-options: {"$locals": -ddump-to-file -ddump-hi}

extra-deps:
  - ed25519-donna-0.1.1
  - megaparsec-8.0.0
  - posix-escape-0.1
  - prettyprinter-1.6.0
  - streaming-events-1.0.1
  - strict-tuple-0.1.3
  - trifecta-2.1
  - which-0.1.0.0
  - witherable-class-0
  - github: kadena-io/chainweb-api
    commit: 98ba7a39e3b699e932c0a3a8f26beafbcf72c175
  - github: kadena-io/pact
    commit: 05197841da68c912756666300c74ce6cec64e3dc
  - github: tathougies/beam
    commit: 2fa99310557e49b37a59e349032ff7236085b6f8
    subdirs:
      - beam-core
      - beam-migrate
      - beam-postgres
  - github: obsidiansystems/gargoyle
    commit: 48ddcca4e977c69ace9b7a67cb2054600c30f8ca
    subdirs:
      - gargoyle
      - gargoyle-postgresql
  - git: https://github.com/kadena-io/thyme.git
    commit: 6ee9fcb026ebdb49b810802a981d166680d867c9
