resolver: lts-14.27

ghc-options: {"$locals": -ddump-to-file -ddump-hi}

extra-deps:
  - posix-escape-0.1
  - streaming-events-1.0.1
  - strict-tuple-0.1.3
  - which-0.1.0.0
  - witherable-class-0
  - github: kadena-io/chainweb-api
    commit: ed82f95111395313476d988a8c531d669593b034
  - github: kadena-io/pact
    commit: 05197841da68c912756666300c74ce6cec64e3dc
  - github: tathougies/beam
    commit: 2fa99310557e49b37a59e349032ff7236085b6f8
    subdirs:
      - beam-core
      - beam-migrate
      - beam-postgres
  - github: obsidiansystems/gargoyle
    commit: 48ddcca4e977c69ace9b7a67cb2054600c30f8ca
    subdirs:
      - gargoyle
      - gargoyle-postgresql
      - gargoyle-postgresql-nix
