resolver: lts-14.27

ghc-options: {"$locals": -ddump-to-file -ddump-hi}

extra-deps:
  - ed25519-donna-0.1.1
  - megaparsec-9.0.0
  - neat-interpolation-0.5.1.2
  - posix-escape-0.1
  - prettyprinter-1.6.0
  - sbv-8.8
  - streaming-events-1.0.1
  - strict-tuple-0.1.3
  - trifecta-2.1
  - which-0.1.0.0
  - witherable-class-0
  - yet-another-logger-0.4.0
  - github: kadena-io/chainweb-api
    commit: fc85edb708853ff08be1c0ca8652de6aa8b9367c
  - github: kadena-io/pact
    commit: 8681a6d6e72eccefe00100f86202d616ab5d1621
  - github: tathougies/beam
    commit: 596981a1ea6765b9f311d48a2ec4d8460ebc4b7e
    subdirs:
      - beam-core
      - beam-migrate
      - beam-postgres
  - github: obsidiansystems/gargoyle
    commit: b0bf855cc91f7cc3b986083af8fbc9da59c86b56
    subdirs:
      - gargoyle
      - gargoyle-postgresql
      - gargoyle-postgresql-connect
  - git: https://github.com/kadena-io/thyme.git
    commit: 6ee9fcb026ebdb49b810802a981d166680d867c9
